- type: entity
  parent: GunSafe
  id: GunSafePistolEnforser
  name: enforser safe
  suffix: Enforser
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolEnforser
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeDominator
  name: dominator safe
  suffix: Dominator
  components:
  - type: StorageFill
    contents:
    - id: WeaponDominator
      amount: 4
